name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SourceMod environment
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.12.x'
      - name: Compile plugin
        run: spcomp -iAnotherIncludeDirectory ./kil-stuck-bots.sp -o output/plugin.smx